import Link from 'next/link';

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-cream flex flex-col pb-24">
      <nav className="border-b border-ink/10 bg-cream/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-2xl mx-auto px-4 h-14 flex items-center gap-3">
          <Link href="/settings" className="text-ink/40 hover:text-ink transition">
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
              <path d="M12 4l-6 6 6 6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </Link>
          <span className="font-serif text-lg font-semibold text-ink">Legal & Privacy</span>
        </div>
      </nav>

      <main className="flex-1 max-w-2xl mx-auto w-full px-4 py-8 space-y-8">

        {/* Disclaimer */}
        <div className="bg-jungle rounded-2xl border border-ink/10 p-6">
          <h2 className="font-serif text-xl font-semibold text-ink mb-3">Important Notice</h2>
          <p className="font-sans text-sm text-ink/60 leading-relaxed">
            Heirlo is a documentation platform, not a law firm. This platform does not provide
            legal advice. The documents generated by Heirlo are personal records of intent and
            are not a substitute for legal advice. Consult a licensed estate attorney in your
            state for legally binding estate planning.
          </p>
        </div>

        {/* Terms of Use */}
        <div className="bg-jungle rounded-2xl border border-ink/10 p-6">
          <h2 className="font-serif text-xl font-semibold text-ink mb-3">Terms of Use</h2>
          <div className="font-sans text-sm text-ink/60 leading-relaxed space-y-3">
            <p>
              By using Heirlo, you agree to these terms. Heirlo provides a platform for
              documenting personal property and intended recipients. The Personal Property
              Memorandum generated by Heirlo is a document of intent only.
            </p>
            <p>
              You are responsible for the accuracy of all information you enter. Heirlo does
              not verify the identity of users or recipients, the ownership of items, or the
              legal validity of any document generated.
            </p>
            <p>
              Heirlo may update these terms at any time. Continued use of the platform
              constitutes acceptance of the updated terms.
            </p>
          </div>
        </div>

        {/* Privacy Policy */}
        <div className="bg-jungle rounded-2xl border border-ink/10 p-6">
          <h2 className="font-serif text-xl font-semibold text-ink mb-3">Privacy Policy</h2>
          <div className="font-sans text-sm text-ink/60 leading-relaxed space-y-3">
            <p>
              Heirlo collects your name, email address, and the item and recipient
              information you provide. Photos are stored securely via Supabase Storage.
            </p>
            <p>
              Your data is used solely to operate the platform and deliver notifications
              to your designated recipients. We do not sell or share your personal
              information with third parties for marketing purposes.
            </p>
            <p>
              Recipient email addresses are used only to send acknowledgment notifications
              on your behalf. Recipients who do not create an account have no data stored
              beyond their name and email as entered by the item owner.
            </p>
          </div>
        </div>

        {/* Contact */}
        <div className="text-center">
          <p className="font-sans text-sm text-ink/40">
            Questions? Contact us at{' '}
            <a href="mailto:hello@heirlo.app" className="text-teal hover:text-teal/80 transition">
              hello@heirlo.app
            </a>
          </p>
        </div>

      </main>
    </div>
  );
}
