'use client';

import { useState, useCallback } from 'react';
import Link from 'next/link';
import type { VaultDocumentData } from '@/lib/pdf/VaultDocument';

function triggerDownload(blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'Heirlo_PPM.pdf';
  a.click();
  URL.revokeObjectURL(url);
}

export function DocumentActions({ data }: { data: VaultDocumentData }) {
  const [downloading, setDownloading] = useState(false);
  const [sharing, setSharing] = useState(false);

  const generateBlob = useCallback(async () => {
    const { pdf } = await import('@react-pdf/renderer');
    const { VaultDocument } = await import('@/lib/pdf/VaultDocument');
    const { createElement } = await import('react');
    // @ts-expect-error react-pdf's pdf() expects its own ReactElement type
    return await pdf(createElement(VaultDocument, { data })).toBlob();
  }, [data]);

  const handleDownload = useCallback(async () => {
    setDownloading(true);
    try {
      const blob = await generateBlob();
      triggerDownload(blob);
    } catch (err) {
      console.error('[document] Download failed:', err);
    } finally {
      setDownloading(false);
    }
  }, [generateBlob]);

  const handleShare = useCallback(async () => {
    setSharing(true);
    try {
      const blob = await generateBlob();
      const file = new File([blob], 'Heirlo_PPM.pdf', { type: 'application/pdf' });

      if (typeof navigator !== 'undefined' && navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          title: 'My Personal Property Memorandum',
          text: 'Personal Property Memorandum generated by Heirlo',
          files: [file],
        });
      } else {
        triggerDownload(blob);
      }
    } catch (err) {
      if (err instanceof Error && err.name !== 'AbortError') {
        console.error('[document] Share failed:', err);
      }
    } finally {
      setSharing(false);
    }
  }, [generateBlob]);

  const isGenerating = downloading || sharing;

  return (
    <div className="flex items-center justify-between px-4 py-3 border-b border-[#F5EFE8]/5">
      <Link href="/settings" className="text-[#F5EFE8]/50 hover:text-[#F5EFE8] transition p-1 -ml-1">
        <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
          <path d="M12 15L7 10L12 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      </Link>
      <h1 className="text-sm font-semibold text-[#F5EFE8]">Your Document</h1>
      <div className="flex gap-2">
        <button
          onClick={handleDownload}
          disabled={isGenerating}
          className="text-xs px-3 py-1.5 rounded-full border border-[#CF9D7B]/40 text-[#CF9D7B] font-medium disabled:opacity-40"
        >
          {downloading ? 'Generating...' : 'Download'}
        </button>
        <button
          onClick={handleShare}
          disabled={isGenerating}
          className="text-xs px-3 py-1.5 rounded-full bg-[#CF9D7B] text-[#0C1519] font-medium disabled:opacity-40"
        >
          {sharing ? 'Generating...' : 'Share'}
        </button>
      </div>
    </div>
  );
}
