'use server';

import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';
import { createClient as createServiceClient } from '@supabase/supabase-js';
import { sendAcknowledgmentEmail } from '@/lib/email';
import { insertSystemEvent } from './events';

function serviceClient() {
  return createServiceClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );
}

export async function addBeneficiary(formData: FormData) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Not authenticated' };

  const item_id = formData.get('item_id') as string;
  const full_name = (formData.get('full_name') as string)?.trim();
  const email = (formData.get('email') as string)?.trim().toLowerCase();
  const requestedPriority = formData.get('priority') as string | null;

  if (!full_name || !email || !item_id) {
    return { error: 'Name and email are required.' };
  }

  if (requestedPriority && !['primary', 'secondary'].includes(requestedPriority)) {
    return { error: 'Invalid beneficiary priority.' };
  }

  // Verify item belongs to this user
  const { data: item } = await supabase
    .from('items')
    .select('id, name')
    .eq('id', item_id)
    .eq('owner_id', user.id)
    .single();

  if (!item) return { error: 'Item not found.' };

  const { data: existingBeneficiaries, error: existingError } = await supabase
    .from('beneficiaries')
    .select('email, priority')
    .eq('item_id', item_id)
    .eq('owner_id', user.id);

  if (existingError) return { error: existingError.message };

  const priority = (requestedPriority as 'primary' | 'secondary' | null)
    ?? (!existingBeneficiaries?.some((ben) => ben.priority === 'primary') ? 'primary' : 'secondary');

  if (existingBeneficiaries?.some((ben) => ben.priority === priority)) {
    return { error: `This item already has a ${priority} beneficiary.` };
  }

  if (existingBeneficiaries?.some((ben) => ben.email.toLowerCase() === email)) {
    return { error: 'This beneficiary is already assigned to this item.' };
  }

  // Get owner profile for email
  const { data: profile } = await supabase
    .from('profiles')
    .select('full_name')
    .eq('id', user.id)
    .single();

  const ownerName = profile?.full_name ?? 'Someone';

  // Create beneficiary
  const { data: beneficiary, error: benError } = await supabase
    .from('beneficiaries')
    .insert({ item_id, owner_id: user.id, full_name, email, priority })
    .select()
    .single();

  if (benError) return { error: benError.message };

  // Create acknowledgment record (token generated by DB default)
  const svc = serviceClient();
  const { data: ack, error: ackError } = await svc
    .from('acknowledgments')
    .insert({ beneficiary_id: beneficiary.id, item_id })
    .select()
    .single();

  if (ackError) {
    // Rollback beneficiary
    await supabase.from('beneficiaries').delete().eq('id', beneficiary.id);
    return { error: ackError.message };
  }

  // Fire-and-forget: log assignment event
  void insertSystemEvent(item_id, 'assigned', `${ownerName.split(' ')[0]} assigned this to ${full_name}`);

  // Send email
  const emailResult = await sendAcknowledgmentEmail({
    recipientEmail: email,
    recipientName: full_name,
    ownerName,
    token: ack.token,
  });

  // If email failed, log it on the acknowledgment but don't block
  if (!emailResult.success) {
    await svc
      .from('acknowledgments')
      .update({ status: 'pending' }) // status stays pending but we could add an email_failed flag in future
      .eq('id', ack.id);
    // Return a soft warning — the beneficiary was saved
    revalidatePath(`/items/${item_id}`);
    revalidatePath('/dashboard');
    return { warning: 'Recipient saved, but the notification email may not have been delivered.' };
  }

  // Fire-and-forget: log notification event
  void insertSystemEvent(item_id, 'notified', `${full_name.split(' ')[0]} was notified by email`);

  revalidatePath(`/items/${item_id}`);
  revalidatePath('/dashboard');
  return { success: true };
}

export async function removeBeneficiary(beneficiaryId: string, itemId: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Not authenticated' };

  const { error } = await supabase
    .from('beneficiaries')
    .delete()
    .eq('id', beneficiaryId)
    .eq('owner_id', user.id);

  if (error) return { error: error.message };

  revalidatePath(`/items/${itemId}`);
  revalidatePath('/dashboard');
  return { success: true };
}

export async function resendNotification(beneficiaryId: string, itemId: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Not authenticated' };

  // Fetch all the info needed
  const svc = serviceClient();

  const { data: ben } = await supabase
    .from('beneficiaries')
    .select('*')
    .eq('id', beneficiaryId)
    .eq('owner_id', user.id)
    .single();

  if (!ben) return { error: 'Beneficiary not found.' };

  const { data: item } = await supabase
    .from('items')
    .select('name')
    .eq('id', itemId)
    .eq('owner_id', user.id)
    .single();

  if (!item) return { error: 'Item not found.' };

  const { data: profile } = await supabase
    .from('profiles')
    .select('full_name')
    .eq('id', user.id)
    .single();

  const ownerName = profile?.full_name ?? 'Someone';

  // Get (or create) acknowledgment
  let { data: ack } = await svc
    .from('acknowledgments')
    .select('token')
    .eq('beneficiary_id', beneficiaryId)
    .eq('item_id', itemId)
    .single();

  if (!ack) {
    const { data: newAck, error: ackError } = await svc
      .from('acknowledgments')
      .insert({ beneficiary_id: beneficiaryId, item_id: itemId })
      .select()
      .single();
    if (ackError) return { error: ackError.message };
    ack = newAck;
  }

  // Update notified_at
  await svc
    .from('acknowledgments')
    .update({ notified_at: new Date().toISOString() })
    .eq('beneficiary_id', beneficiaryId)
    .eq('item_id', itemId);

  const emailResult = await sendAcknowledgmentEmail({
    recipientEmail: ben.email,
    recipientName: ben.full_name,
    ownerName,
    token: ack!.token,
  });

  revalidatePath(`/items/${itemId}`);

  if (!emailResult.success) {
    return { warning: 'Email may not have been delivered: ' + emailResult.error };
  }

  return { success: true };
}

export async function updateItemDescription(itemId: string, description: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Not authenticated' };

  const { error } = await supabase
    .from('items')
    .update({ description: description.trim() })
    .eq('id', itemId)
    .eq('owner_id', user.id);

  if (error) return { error: error.message };

  // Fire-and-forget: log story edit event
  const { data: profile } = await supabase
    .from('profiles')
    .select('full_name')
    .eq('id', user.id)
    .single();
  const firstName = (profile?.full_name ?? 'Owner').split(' ')[0];
  void insertSystemEvent(itemId, 'story_edited', `${firstName} updated the story`);

  revalidatePath(`/items/${itemId}`);
  return { success: true };
}

export async function deleteItemWithCheck(itemId: string, force = false) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Not authenticated' };

  // Check ownership and get item name
  const { data: item } = await supabase
    .from('items')
    .select('id, name')
    .eq('id', itemId)
    .eq('owner_id', user.id)
    .single();

  if (!item) return { error: 'Item not found.' };

  const svc = serviceClient();

  if (!force) {
    const { data: pending } = await svc
      .from('acknowledgments')
      .select('id')
      .eq('item_id', itemId)
      .eq('status', 'pending');

    if (pending && pending.length > 0) {
      return { hasPending: true, pendingCount: pending.length };
    }
  }

  // Get owner profile for notification emails
  const { data: profile } = await supabase
    .from('profiles')
    .select('full_name')
    .eq('id', user.id)
    .single();

  const ownerFullName = profile?.full_name ?? 'Someone';
  const ownerFirstName = ownerFullName.split(' ')[0];

  // Fetch beneficiaries + their ack status for notification
  const { data: benRows } = await svc
    .from('beneficiaries')
    .select('id, full_name, email')
    .eq('item_id', itemId);

  const bensToNotify: { full_name: string; email: string }[] = [];

  if (benRows && benRows.length > 0) {
    const benIds = benRows.map((b: { id: string }) => b.id);
    const { data: ackRows } = await svc
      .from('acknowledgments')
      .select('beneficiary_id, status')
      .in('beneficiary_id', benIds);

    const ackMap = new Map(
      (ackRows ?? []).map((a: { beneficiary_id: string; status: string }) => [a.beneficiary_id, a.status])
    );

    for (const ben of benRows as { id: string; full_name: string; email: string }[]) {
      const status = ackMap.get(ben.id);
      if (status === 'pending' || status === 'accepted') {
        bensToNotify.push({ full_name: ben.full_name, email: ben.email });
      }
    }
  }

  // Send cancellation emails before deleting
  if (bensToNotify.length > 0) {
    const { Resend } = await import('resend');
    const resend = new Resend(process.env.RESEND_API_KEY!);

    await Promise.allSettled(
      bensToNotify.map(async (ben) => {
        const recipientFirst = ben.full_name.split(' ')[0];
        try {
          await resend.emails.send({
            from: 'Heirlo <notifications@heirlo.app>',
            to: ben.email,
            subject: `${ownerFirstName} has updated their vault`,
            html: `<p>Hi ${recipientFirst},</p>
<p>${ownerFullName} has removed &ldquo;${item.name}&rdquo; from their Heirlo vault.</p>
<p>Your assignment for this item has been cancelled. If you have questions, you can reach ${ownerFirstName} directly.</p>
<p style="margin-top:24px;color:#999;font-size:12px;">&mdash; The Heirlo Team<br/>Heirlo is not a law firm &middot; Not legal advice &middot; Document of intent only</p>`,
            text: `Hi ${recipientFirst},\n\n${ownerFullName} has removed "${item.name}" from their Heirlo vault.\n\nYour assignment for this item has been cancelled. If you have questions, you can reach ${ownerFirstName} directly.\n\n— The Heirlo Team\nHeirlo is not a law firm · Not legal advice · Document of intent only`,
          });
        } catch (err) {
          console.error(`[delete] Failed to send cancellation email to ${ben.email}:`, err);
        }
      })
    );
  }

  // Delete the item (cascades to beneficiaries + acknowledgments)
  const { error } = await supabase
    .from('items')
    .delete()
    .eq('id', itemId)
    .eq('owner_id', user.id);

  if (error) return { error: error.message };

  revalidatePath('/dashboard');
  return { deleted: true };
}
